dataset_path: ../dataset
data_yaml: ../dataset/data.yaml
model_name: yolov8s-worldv2.pt
runs_dir: ../runs
imgsz: 640
num_epochs: 50
batch_size: 10
lr0: 2e-05
weight_decay: 0.0005
patience: 10
rect: false
device: cuda
