dataset_path: ../dataset
data_yaml: ../dataset/data.yaml
model_name: yolov8n
runs_dir: ../runs
imgsz: 640
num_epochs: 100
batch_size: 10
lr0: 2e-05
weight_decay: 0.0005
patience: 20
rect: false
device: cuda
