dataset_path: ../dataset
test_dir: ../dataset/test/images
test_labels_dir: ../dataset/test/labels
temp_test_dir: ../test_aug
test_runs_dir: ../test_runs
runs_dir: ../runs
yolo_type: yolo11n
model_weights: ../runs/yolo11n_train/weights/best.pt
train_config_path: ../runs/yolo11n_train/train_config.yaml
imgsz: 320
confidence_thresh: 0.35
max_brightness_percentage: 0.4
max_zoom_percentage: 0.3
device: cuda
